version: '3.4'

services:
  apstokenserver:
    image: aps-token-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8090:8090
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "config.js"]
