version: '3.4'

services:
  forgetokenserver:
    image: forgetokenserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8090:8090
