version: '3.4'

services:
  apstokenserver:
    image: aps-token-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8090:8090
